=== minakmostoles/DAM/LMSGI/Tarea 4.1/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>Creado por Mario Rubio Avila el 01/2019 Tarea 4.1 LMSGI DAMEL </xs:documentation>
	</xs:annotation>
	<xs:element name="pedidos">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="pedido" minOccurs="0" maxOccurs="unbounded"> 
					<xs:complexType>
						<xs:sequence>			
							<xs:element name="sucursal" type="xs:string"/>
							<xs:element name="dir_entrega" type="xs:string"/>
							<xs:element name="nom_trabajador" type="xs:string"/>
							<xs:element name="f_pedido" type="xs:date"/>
							<xs:element name="obs_pedido">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Urgente"/>
										<xs:enumeration value="Incompleto"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="plazo_revision" type="xs:integer"/>
							<xs:element name="articulo" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="unidades" type="xs:decimal"/><!--Puede ser entero pero lo pongo decimal por si alguna vez la unidad es metros o por peso-->
										<xs:element name="precio_und" type="xs:decimal"/>
										<xs:element name="obs_articulo" type="xs:string"/>
									</xs:sequence>
									<xs:attribute name="cod_articulo" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="cod_pedido" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[a-zA-Z]{1}[a-zA-Z0-9]{7}"/>
									</xs:restriction>
								</xs:simpleType>
						</xs:attribute>
						
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== minakmostoles/DAM/LMSGI/Tarea 4.1/pedidosXSD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pedidos.xsd">
	<pedido cod_pedido="A1234567"><!--Formado por una cadena de 8 caracteres de los cuales el primero es una letra-->
		<!--CENTRO ADMINISTRATIVO Y INFORMACION ENVIO-->
		<sucursal></sucursal><!--Datos de la sucursal que realiza el pedido-->
		<dir_entrega></dir_entrega><!--Direcciones para los envíos correspondientes-->
		<!--PEDIDO-->
		<nom_trabajador></nom_trabajador><!--Nombre del trabajador que realiza el pedido.-->
		<f_pedido>2001-10-26</f_pedido><!--Fecha del pedido.-->
		<obs_pedido>Incompleto</obs_pedido><!--Observaciones sobre el pedido, cuyos valores son, en caso de que exista el dato: urgente o incompleto.-->
		<plazo_revision>4</plazo_revision><!--Plazo de revisión de los productos recibidos que será un intervalo de tiempo expresado en días y dependerá del precio final del pedido.-->
		<!--ARTICULO-->
		<articulo cod_articulo="Articulo Test"><!--Código del artículo, formado por tres letras mayúsculas y tres dígitos separados por un guión. Es la referencia que tiene que dar el ordenante a la sede en caso de devolución de algún artículo.-->
			<unidades>1</unidades><!--Número de unidades pedidas.-->
			<precio_und>10</precio_und><!--Precio de cada unidad.-->
			<obs_articulo></obs_articulo><!--Observaciones del artículo.-->
		</articulo>
	</pedido>
</pedidos>
